// <auto-generated />
using System;
using Lab2.RezervacijeProstora;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2.RezervacijeProstora.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506224727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KorisnickoIme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipKorisnika")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Drzava")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostanskiBroj")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Oprema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ispravna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Proizvodac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Vrijednost")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Oprema");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Placanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojTransakcije")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPlacanja")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RezervacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Uspjesno")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RezervacijaId")
                        .IsUnique();

                    b.ToTable("Placanja");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.ProstorZaProbu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CijenaPoSatu")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DatumDodavanja")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImaKlimu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImaParking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KapacitetOsoba")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LokacijaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("VlasnikId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LokacijaId");

                    b.HasIndex("VlasnikId");

                    b.ToTable("Prostori");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumRecenzije")
                        .HasColumnType("TEXT");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocjena")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProstorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ProstorId");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojSudionika")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumVrijemeDo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumVrijemeOd")
                        .HasColumnType("TEXT");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProstorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ProstorId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Vlasnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrojTelefona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vlasnici");
                });

            modelBuilder.Entity("ProstorOprema", b =>
                {
                    b.Property<int>("OpremaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProstoriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OpremaId", "ProstoriId");

                    b.HasIndex("ProstoriId");

                    b.ToTable("ProstorOprema");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Placanje", b =>
                {
                    b.HasOne("Lab2.RezervacijeProstora.Models.Rezervacija", "Rezervacija")
                        .WithOne("Placanje")
                        .HasForeignKey("Lab2.RezervacijeProstora.Models.Placanje", "RezervacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.ProstorZaProbu", b =>
                {
                    b.HasOne("Lab2.RezervacijeProstora.Models.Lokacija", "Lokacija")
                        .WithMany("Prostori")
                        .HasForeignKey("LokacijaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab2.RezervacijeProstora.Models.Vlasnik", "Vlasnik")
                        .WithMany("Prostori")
                        .HasForeignKey("VlasnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lokacija");

                    b.Navigation("Vlasnik");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Recenzija", b =>
                {
                    b.HasOne("Lab2.RezervacijeProstora.Models.Korisnik", "Korisnik")
                        .WithMany("Recenzije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab2.RezervacijeProstora.Models.ProstorZaProbu", "Prostor")
                        .WithMany("Recenzije")
                        .HasForeignKey("ProstorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Prostor");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Rezervacija", b =>
                {
                    b.HasOne("Lab2.RezervacijeProstora.Models.Korisnik", "Korisnik")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lab2.RezervacijeProstora.Models.ProstorZaProbu", "Prostor")
                        .WithMany("Rezervacije")
                        .HasForeignKey("ProstorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Prostor");
                });

            modelBuilder.Entity("ProstorOprema", b =>
                {
                    b.HasOne("Lab2.RezervacijeProstora.Models.Oprema", null)
                        .WithMany()
                        .HasForeignKey("OpremaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2.RezervacijeProstora.Models.ProstorZaProbu", null)
                        .WithMany()
                        .HasForeignKey("ProstoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Korisnik", b =>
                {
                    b.Navigation("Recenzije");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Lokacija", b =>
                {
                    b.Navigation("Prostori");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.ProstorZaProbu", b =>
                {
                    b.Navigation("Recenzije");

                    b.Navigation("Rezervacije");
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Rezervacija", b =>
                {
                    b.Navigation("Placanje")
                        .IsRequired();
                });

            modelBuilder.Entity("Lab2.RezervacijeProstora.Models.Vlasnik", b =>
                {
                    b.Navigation("Prostori");
                });
#pragma warning restore 612, 618
        }
    }
}
